#!/usr/bin/env node

// Automated setup script for Go Leadership App
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Colors for console output
const colors = {
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
  reset: '\x1b[0m'
};

function colorLog(color, message) {
  console.log(colors[color] + message + colors.reset);
}

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function createDirectories() {
  const directories = ['public', 'templates'];
  
  for (const dir of directories) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      colorLog('green', `✅ Created directory: ${dir}`);
    } else {
      colorLog('yellow', `⚪ Directory already exists: ${dir}`);
    }
  }
}

async function createEnvFile() {
  colorLog('cyan', '\n📝 Setting up environment variables...');
  
  if (fs.existsSync('.env')) {
    const overwrite = await askQuestion('❓ .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      colorLog('yellow', '⚪ Skipping .env file creation');
      return;
    }
  }
  
  colorLog('blue', '\nPlease provide the following information:');
  
  // PostgreSQL Database URL
  colorLog('magenta', '\n🐘 PostgreSQL Configuration:');
  const databaseUrl = await askQuestion('📊 DATABASE_URL (PostgreSQL connection string): ');
  if (!databaseUrl) {
    colorLog('yellow', '⚠️  No DATABASE_URL provided. Using Replit default.');
    colorLog('blue', '💡 Replit will automatically provide DATABASE_URL environment variable');
  }
  
  const openaiKey = await askQuestion('🤖 OpenAI API Key (required): ');
  if (!openaiKey) {
    colorLog('red', '❌ OpenAI API Key is required for the app to function');
    process.exit(1);
  }
  
  const emailUser = await askQuestion('📧 Email address (Gmail recommended): ');
  if (!emailUser) {
    colorLog('red', '❌ Email address is required');
    process.exit(1);
  }
  
  const emailPassword = await askQuestion('🔐 Email password/app password: ');
  if (!emailPassword) {
    colorLog('red', '❌ Email password is required');
    process.exit(1);
  }
  
  const port = await askQuestion('🌐 Port (default 5000): ') || '5000';
  const adminPassword = await askQuestion('🔒 Admin dashboard password (default: admin123): ') || 'admin123';
  
  const envContent = `# Go Leadership App Environment Variables (PostgreSQL)
# Generated by setup script on ${new Date().toISOString()}

# PostgreSQL Database Configuration
${databaseUrl ? `DATABASE_URL=${databaseUrl}` : '# DATABASE_URL=postgresql://username:password@localhost:5432/database_name'}
${!databaseUrl ? '# Note: Replit provides DATABASE_URL automatically' : ''}

# OpenAI API Configuration
OPENAI_API_KEY=${openaiKey}

# Email Configuration
EMAIL_USER=${emailUser}
EMAIL_PASSWORD=${emailPassword}

# Server Configuration
PORT=${port}

# Admin Configuration
ADMIN_PASSWORD=${adminPassword}

# Environment
NODE_ENV=development

# Optional: Custom SMTP (leave blank to use Gmail)
# SMTP_HOST=smtp.your-provider.com
# SMTP_PORT=587
`;
  
  fs.writeFileSync('.env', envContent);
  colorLog('green', '✅ .env file created successfully');
}colorLog('blue', '\nPlease provide the following information:');
  
  const openaiKey = await askQuestion('🤖 OpenAI API Key (required): ');
  if (!openaiKey) {
    colorLog('red', '❌ OpenAI API Key is required for the app to function');
    process.exit(1);
  }
  
  const emailUser = await askQuestion('📧 Email address (Gmail recommended): ');
  if (!emailUser) {
    colorLog('red', '❌ Email address is required');
    process.exit(1);
  }
  
  const emailPassword = await askQuestion('🔐 Email password/app password: ');
  if (!emailPassword) {
    colorLog('red', '❌ Email password is required');
    process.exit(1);
  }
  
  const port = await askQuestion('🌐 Port (default 5000): ') || '5000';
  const adminPassword = await askQuestion('🔒 Admin dashboard password (default: admin123): ') || 'admin123';
  
  const envContent = `# Go Leadership App Environment Variables
# Generated by setup script on ${new Date().toISOString()}

# OpenAI API Configuration
OPENAI_API_KEY=${openaiKey}

# Email Configuration
EMAIL_USER=${emailUser}
EMAIL_PASSWORD=${emailPassword}

# Server Configuration
PORT=${port}

# Admin Configuration
ADMIN_PASSWORD=${adminPassword}

# Environment
NODE_ENV=development

# Optional: Custom SMTP (leave blank to use Gmail)
# SMTP_HOST=smtp.your-provider.com
# SMTP_PORT=587
`;
  
  fs.writeFileSync('.env', envContent);
  colorLog('green', '✅ .env file created successfully');
}

async function validateSetup() {
  colorLog('cyan', '\n🔍 Validating setup...');
  
  // Check required files
  const requiredFiles = [
    'package.json',
    'server.js',
    'database.js',
    'aiService.js',
    'emailService.js',
    'scheduler.js',
    '.env'
  ];
  
  let missingFiles = [];
  
  for (const file of requiredFiles) {
    if (fs.existsSync(file)) {
      colorLog('green', `✅ ${file}`);
    } else {
      colorLog('red', `❌ ${file}`);
      missingFiles.push(file);
    }
  }
  
  if (missingFiles.length > 0) {
    colorLog('red', `\n❌ Missing required files: ${missingFiles.join(', ')}`);
    return false;
  }
  
  // Check frontend files
  const frontendFiles = [
    'public/index.html',
    'public/style.css',
    'public/script.js',
    'public/admin.html',
    'public/success.html'
  ];
  
  for (const file of frontendFiles) {
    if (fs.existsSync(file)) {
      colorLog('green', `✅ ${file}`);
    } else {
      colorLog('yellow', `⚠️  ${file} - Will be created by artifacts`);
    }
  }
  
  // Check templates
  const templateFiles = [
    'templates/welcome.html',
    'templates/weekly.html'
  ];
  
  for (const file of templateFiles) {
    if (fs.existsSync(file)) {
      colorLog('green', `✅ ${file}`);
    } else {
      colorLog('yellow', `⚠️  ${file} - Will be created by artifacts`);
    }
  }
  
  return true;
}

async function installDependencies() {
  colorLog('cyan', '\n📦 Checking dependencies...');
  
  if (!fs.existsSync('node_modules')) {
    const install = await askQuestion('❓ Install dependencies with npm? (Y/n): ');
    if (install.toLowerCase() !== 'n') {
      colorLog('blue', '📥 Installing dependencies...');
      
      const { spawn } = require('child_process');
      
      return new Promise((resolve, reject) => {
        const npm = spawn('npm', ['install'], { stdio: 'inherit' });
        
        npm.on('close', (code) => {
          if (code === 0) {
            colorLog('green', '✅ Dependencies installed successfully');
            resolve();
          } else {
            colorLog('red', '❌ Failed to install dependencies');
            reject(new Error('npm install failed'));
          }
        });
      });
    }
  } else {
    colorLog('green', '✅ Dependencies already installed');
  }
}

async function testConfiguration() {
  colorLog('cyan', '\n🧪 Testing configuration...');
  
  // Load environment variables
  require('dotenv').config();
  
  // Test OpenAI API Key
  if (process.env.OPENAI_API_KEY) {
    colorLog('green', '✅ OpenAI API Key configured');
  } else {
    colorLog('red', '❌ OpenAI API Key missing');
    return false;
  }
  
  // Test email configuration
  if (process.env.EMAIL_USER && process.env.EMAIL_PASSWORD) {
    colorLog('green', '✅ Email configuration found');
  } else {
    colorLog('red', '❌ Email configuration incomplete');
    return false;
  }
  
  // Test PostgreSQL database connection
  if (process.env.DATABASE_URL) {
    colorLog('green', '✅ DATABASE_URL configured');
    try {
      const { testConnection } = require('./database');
      const connected = await testConnection();
      if (connected) {
        colorLog('green', '✅ PostgreSQL connection successful');
      } else {
        colorLog('red', '❌ PostgreSQL connection failed');
        return false;
      }
    } catch (error) {
      colorLog('red', `❌ PostgreSQL connection test failed: ${error.message}`);
      return false;
    }
  } else {
    colorLog('yellow', '⚠️  DATABASE_URL not set - this is normal on Replit');
    colorLog('blue', '💡 Replit will provide DATABASE_URL automatically when deployed');
  }
  
  // Test database initialization
  try {
    const { initDatabase } = require('./database');
    await initDatabase();
    colorLog('green', '✅ Database initialized successfully');
  } catch (error) {
    colorLog('red', `❌ Database initialization failed: ${error.message}`);
    colorLog('yellow', '💡 Try running: npm run migrate up');
    return false;
  }
  
  return true;
}

async function runMigrations() {
  colorLog('cyan', '\n🗃️  Running database migrations...');
  
  try {
    const { migrateUp } = require('./migrations/migrate');
    await migrateUp();
    colorLog('green', '✅ Database migrations completed');
    return true;
  } catch (error) {
    colorLog('red', `❌ Migration failed: ${error.message}`);
    return false;
  }
}

async function showCompletionMessage() {
  colorLog('green', '\n🎉 PostgreSQL Setup completed successfully!');
  colorLog('cyan', '\n📋 Next steps:');
  console.log('');
  console.log('1. Run database migrations:');
  colorLog('blue', '   npm run migrate up');
  console.log('');
  console.log('2. (Optional) Create sample data:');
  colorLog('blue', '   npm run migrate sample');
  console.log('');
  console.log('3. Start the application:');
  colorLog('blue', '   npm start');
  console.log('');
  console.log('4. Or use the startup script:');
  colorLog('blue', '   ./start.sh');
  console.log('');
  console.log('5. Visit your application:');
  colorLog('blue', `   http://localhost:${process.env.PORT || 5000}`);
  console.log('');
  console.log('6. Access admin dashboard:');
  colorLog('blue', `   http://localhost:${process.env.PORT || 5000}/admin`);
  console.log('');
  console.log('7. Run tests:');
  colorLog('blue', '   npm test');
  colorLog('blue', '   npm run test -- --all');
  console.log('');
  console.log('8. Check migration status:');
  colorLog('blue', '   npm run migrate status');
  console.log('');
  colorLog('magenta', '🐘 PostgreSQL Features:');
  colorLog('magenta', '   • Scalable database with connection pooling');
  colorLog('magenta', '   • ACID compliance and data integrity');
  colorLog('magenta', '   • Advanced indexing for better performance');
  colorLog('magenta', '   • Automatic migrations and schema management');
  console.log('');
  colorLog('magenta', '📚 Documentation: Check README.md for more information');
  colorLog('magenta', '🐛 Issues: Report bugs on GitHub');
  colorLog('magenta', '💬 Support: Email support@go-leadership.app');
}

async function generateStartupScript() {
  const startScript = `#!/bin/bash
# Go Leadership App Startup Script
# Generated by setup script

echo "🚀 Starting Go Leadership App..."

# Check if .env exists
if [ ! -f .env ]; then
    echo "❌ .env file not found. Run setup.js first."
    exit 1
fi

# Check if node_modules exists
if [ ! -d node_modules ]; then
    echo "📦 Installing dependencies..."
    npm install
fi

# Start the application
echo "🎯 Go Leadership App starting on port \${PORT:-5000}"
npm start
`;

  fs.writeFileSync('start.sh', startScript);
  
  // Make executable on Unix systems
  try {
    fs.chmodSync('start.sh', '755');
    colorLog('green', '✅ Created start.sh script');
  } catch (error) {
    colorLog('yellow', '⚠️  Created start.sh (chmod failed - you may need to make it executable manually)');
  }
}

async function showCompletionMessage() {
  colorLog('green', '\n🎉 Setup completed successfully!');
  colorLog('cyan', '\n📋 Next steps:');
  console.log('');
  console.log('1. Start the application:');
  colorLog('blue', '   npm start');
  console.log('');
  console.log('2. Or use the startup script:');
  colorLog('blue', '   ./start.sh');
  console.log('');
  console.log('3. Visit your application:');
  colorLog('blue', `   http://localhost:${process.env.PORT || 5000}`);
  console.log('');
  console.log('4. Access admin dashboard:');
  colorLog('blue', `   http://localhost:${process.env.PORT || 5000}/admin`);
  console.log('');
  console.log('5. Run tests:');
  colorLog('blue', '   npm test');
  colorLog('blue', '   npm run test -- --all');
  console.log('');
  colorLog('magenta', '📚 Documentation: Check README.md for more information');
  colorLog('magenta', '🐛 Issues: Report bugs on GitHub');
  colorLog('magenta', '💬 Support: Email support@go-leadership.app');
}

async function main() {
  console.clear();
  colorLog('cyan', '🚀 Go Leadership App Setup (PostgreSQL)');
  colorLog('cyan', '=======================================\n');
  
  try {
    // Welcome message
    colorLog('blue', 'Welcome! This script will help you set up your Go Leadership App with PostgreSQL.');
    colorLog('yellow', 'Make sure you have Node.js 18+ and npm installed.\n');
    colorLog('magenta', '🐘 This version uses PostgreSQL 15 - perfect for Replit deployment!\n');
    
    const proceed = await askQuestion('❓ Continue with setup? (Y/n): ');
    if (proceed.toLowerCase() === 'n') {
      colorLog('yellow', '👋 Setup cancelled');
      process.exit(0);
    }
    
    // Create directories
    colorLog('cyan', '\n📁 Creating directories...');
    await createDirectories();
    
    // Create migrations directory
    if (!fs.existsSync('migrations')) {
      fs.mkdirSync('migrations', { recursive: true });
      colorLog('green', '✅ Created directory: migrations');
    } else {
      colorLog('yellow', '⚪ Directory already exists: migrations');
    }
    
    // Create .env file
    await createEnvFile();
    
    // Install dependencies
    await installDependencies();
    
    // Validate setup
    const setupValid = await validateSetup();
    if (!setupValid) {
      colorLog('red', '\n❌ Setup validation failed');
      process.exit(1);
    }
    
    // Run database migrations
    const migrationsRun = await runMigrations();
    if (!migrationsRun) {
      colorLog('yellow', '\n⚠️  Migration failed - you may need to run them manually later');
    }
    
    // Test configuration
    const configValid = await testConfiguration();
    if (!configValid) {
      colorLog('red', '\n❌ Configuration test failed');
      colorLog('yellow', '💡 Please check your .env file and DATABASE_URL');
      colorLog('yellow', '💡 On Replit, DATABASE_URL is provided automatically');
      process.exit(1);
    }
    
    // Generate startup script
    await generateStartupScript();
    
    // Show completion message
    await showCompletionMessage();
    
  } catch (error) {
    colorLog('red', `\n❌ Setup failed: ${error.message}`);
    process.exit(1);
  } finally {
    rl.close();
  }
}

// Show help
function showHelp() {
  console.log(`
🚀 Go Leadership App Setup Script (PostgreSQL)

This script will help you set up your Go Leadership App with PostgreSQL by:
- Creating necessary directories
- Setting up environment variables (including DATABASE_URL)
- Installing dependencies
- Running database migrations
- Testing PostgreSQL configuration
- Creating startup scripts

Usage:
  node setup.js        # Run interactive setup
  node setup.js --help # Show this help

Requirements:
- Node.js 18+
- npm
- PostgreSQL 15 (provided by Replit)
- OpenAI API key
- Email account (Gmail recommended)

For Replit deployment:
- DATABASE_URL is automatically provided
- PostgreSQL 15 is pre-configured
- No additional database setup required

For more information, visit: https://github.com/yourusername/go-leadership-app
`);
}

// Run setup if called directly
if (require.main === module) {
  const args = process.argv.slice(2);
  
  if (args.includes('--help') || args.includes('-h')) {
    showHelp();
    process.exit(0);
  }
  
  main().catch(error => {
    colorLog('red', `Setup error: ${error.message}`);
    process.exit(1);
  });
}

module.exports = { main };